import React from 'react';
import './SamplePanel.css';
import SampleTile from '../SampleTile/SampleTile';

const SamplePanel = () => {
    return ( 
        <div className="sample__panel">
            <SampleTile cover={"1"} currText="The patient is a 47-year-old female with a history of human immunodeficiency virus (last CD4 count 42 and a viral load of 65,000), cirrhosis, diabetes, and hypothyroidism presented with eight days of fevers to 104, chills, shortness of breath, cough, dyspnea on exertion, and fatigue.  The patient states she has become progressively dyspneic to the point where she is short of breath with speaking.  She has also had night sweats for the past two days and whitish sputum.  She complains of myalgias.  No recent ill contacts. Known tuberculosis exposure.  In the Emergency Department, the patient was initially 96% on room air, with a respiratory rate of 20, and a heart rate of 117.  A chest x-ray showed diffuse interstitial opacities. She received 3 liters of normal saline, clindamycin, and primaquine for likely Pneumocystis carinii pneumonia.  She became progressively dyspneic with her respiratory rate increasing to 40, and her oxygen saturations dropping to 89% on room air.  She was placed on 6 liters by nasal cannula, and an arterial blood gas showed 7.47/28/74.  The patient was given prednisone and aztreonam for possible cholangitis."/>
            <SampleTile cover={"2"} currText="Patient is 53 year-old male with aortic stenosis coronary artery disease and patient has s p coronary artery bypass graft x3 dr at a bilateral lower extremity claudication. Patient has peripheral vascular disease . Patient also has diabetes mellitus along with inflammatory arthritis and glaucoma cabg x lima to lad svg to om1 svg to om . Patient underwent serial echocardiograms given worsening dyspnea on exertion and exertional angina he has been referred for a redo sternotomy and aortic valve replacement."/>
            <SampleTile cover={"3"} currText="Patient has primary pneumonia sputum positive for methicillin resistant staph aureus seizure history describes as mal but was previously described as tonic clonic with bilateral arm shaking no loc was on trileptal in the past but was weaned off due to associated hyponatremia now on keppra followed by dr eeg negative headaches taken multiple narcotics in the past to treat this in addition to advil and tylenol it was described in prior notes as starting on the left side of his head and radiating anteriorly and down his back he also has had documented left face pain type ii dm peripheral neuropathy hypertension hypercholesterolemia diastolic dysfunction ef on recent echo with lvh gerd depression anxiety lumbar spinal stenosis w history c3 c7 fractures neurogenic bladder s p left cataract surgery vitamin b12 deficiency atypical cp last mibi negative hyponatremia baseline h o multiple falls due to multifactorial gait ataxia also followed by dr mm thecal mass stable over several years consistent with nerve sheath tumor likely prior left temporal infarct per atrophy on head mri micu hpi hypotension arf"/>
            <SampleTile cover={"4"} currText="Patient underwent serial echocardiograms given worsening dyspnea on exertion and exertional angina he has been referred for a redo sternotomy and aortic valve replacement. Patient is 53 year-old male with aortic stenosis coronary artery disease and patient has s p coronary artery bypass graft x3 dr at a bilateral lower extremity claudication. Patient has peripheral vascular disease . Patient also has diabetes mellitus along with inflammatory arthritis and glaucoma cabg x lima to lad svg to om1 svg to om . "/>
            <SampleTile cover={"5"} currText="thrombosis of distal branch of right portal vein compression fracture l3 alcoholic cirrhosis diabetes hypertension mild pulmonary artery hypertension cri baseline cr up to vitamin b12 deficiency rectal adenoma herniated lumbar disk gastritis hyperkalemiamr is a 61m s p a simultaneous liver and kidney transplant in he was recently hospitalized and had a portal vein shunt placed on for portal vein stenosis on wednesday he states that he experienced the acute onset of sharp constant out of left flank pain that radiates down his left side and to his anterior abdomen he denies any recent trauma or strenuous exertion turning his upper body aggravates the pain and tylenol relieves the pain he underwent a ct scan the next day that revealed a thrombosed distal branch of the right portal vein no ascites or focal hepatic lesions were seen no hernias were seen he denies dyspnea and chest pain he denies fevers chills nausea vomiting and diarrhea he is able to tolerate food he denies dysuria and hematuria thrombosis of distal branch of right portal vein"/>
        </div>
    );
}

export default SamplePanel;