import React from 'react';
import './SamplePanel.css';
import SampleTile from '../SampleTile/SampleTile';

const SamplePanel = () => {
    return ( 
        <div className="sample__panel">
            <SampleTile cover={"1"} currText="The patient is a 47-year-old female with a history of human immunodeficiency virus (last CD4 count 42 and a viral load of 65,000), cirrhosis, diabetes, and hypothyroidism presented with eight days of fevers to 104, chills, shortness of breath, cough, dyspnea on exertion, and fatigue.  The patient states she has become progressively dyspneic to the point where she is short of breath with speaking.  She has also had night sweats for the past two days and whitish sputum.  She complains of myalgias.  No recent ill contacts.Known tuberculosis exposure.  In the Emergency Department, the patient was initially 96% on room air, with a respiratory rate of 20, and a heart rate of 117.  A chest x-ray showed diffuse interstitial opacities. She received 3 liters of normal saline, clindamycin, and primaquine for likely Pneumocystis carinii pneumonia.  She spiked a temperature to 102.1 and became progressively dyspneic with her respiratory rate increasing to 40, and her oxygen saturations dropping to 89% on room air.  She was placed on 6 liters by nasal cannula, and an arterial blood gas showed 7.47/28/74.  The patient was given prednisone and aztreonam for possible cholangitis."/>
            <SampleTile cover={"2"} currText="is aortic stenosis coronary artery disease s p coronary artery bypass graft x3 dr at a bilateral lower extremity claudication peripheral vascular disease diabetes mellitus inflammatory arthritis glaucoma cabg x lima to lad svg to om1 svg to om bilateral femoral endarterectomies tonsillectomy left vitrectomy s76 year old male with prior coronary artery grafts in at the hospital who has known severe aortic stenosis which was being followed by serial echocardiograms given worsening dyspnea on exertion and exertional angina he has been referred for a redo sternotomy and aortic valve replacement aortic stenosis"/>
            <SampleTile cover={"3"} currText="primary pneumonia sputum positive for methicillin resistant staph aureus seizure history describes as mal but was previously described as tonic clonic with bilateral arm shaking no loc was on trileptal in the past but was weaned off due to associated hyponatremia now on keppra followed by dr eeg negative headaches taken multiple narcotics in the past to treat this in addition to advil and tylenol it was described in prior notes as starting on the left side of his head and radiating anteriorly and down his back he also has had documented left face pain type ii dm peripheral neuropathy hypertension hypercholesterolemia diastolic dysfunction ef on recent echo with lvh gerd depression anxiety lumbar spinal stenosis w history c3 c7 fractures neurogenic bladder s p left cataract surgery vitamin b12 deficiency atypical cp last mibi negative hyponatremia baseline h o multiple falls due to multifactorial gait ataxia also followed by dr mm thecal mass stable over several years consistent with nerve sheath tumor likely prior left temporal infarct per atrophy on head mri micu hpi hypotension arf"/>
            <SampleTile cover={"4"} currText="primary diagnosis esophageal variceal bleed secondary diagnosis liver avmsp tablet s refills tion home hepatitis c cirrhosis s p interferon with svr giii esophageal varices gerd htn diverticulosis rbbb hiatal hernia esophogeal spasm eczema herpes simplex s p lipoma removal mrsa buttock abscess s p tonsillectomy s p lap ccy pml fissure s p botox and perianal dermatitis51 yo m with hcv s p interferon ribavirin with sustained virologic response cirrhosis liver avm giii esophageal varices presents with one day of melena and hematemesis the patient was admitted to from to for abdominal pain of unclear etiology during that admission his work up egd with g3 esophageal varices which were not seen on egd he also underwent a liver mri which showed a liver avm which was believed to be worsening his portal hypertension he was scheduled for a planned ir coiling of his avm tomorrow however yesterday he had an episode of melena brbpr and today had what he describes as one cups of hematemesis he denies dizziness or lightheadedness but does endorse crampy abd pain egd findings esophagus protruding lesions cords of grade iii varices were seen in the lower third of the esophagus there were stigmata of recent bleeding bands were successfully placed stomach contents clotted blood was seen in the fundus there was no gastric varix underneath duodenum normal duodenum impression varices at the lower third of the esophagus ligation blood in the fundus otherwise normal egd to second part of the duodenum hepatic angiogram by ir high flow arterioportal fistula supplied by the right hepatic arteryinvolving the border zone parenchyma between the segments vii and viii of the right hepatic lobe successful deployment of a mm amplatzer endovascular plug effectively shutting down the flow through the arterioportal fistula variant early origin of the right hepatic lobar artery directly from the celiac trunk successful deployment of french angio seal closure device in the right common femoral artery melena hematemesis"/>
            <SampleTile cover={"5"} currText="thrombosis of distal branch of right portal vein compression fracture l3 alcoholic cirrhosis diabetes hypertension mild pulmonary artery hypertension cri baseline cr up to vitamin b12 deficiency rectal adenoma herniated lumbar disk gastritis hyperkalemiamr is a 61m s p a simultaneous liver and kidney transplant in he was recently hospitalized and had a portal vein shunt placed on for portal vein stenosis on wednesday he states that he experienced the acute onset of sharp constant out of left flank pain that radiates down his left side and to his anterior abdomen he denies any recent trauma or strenuous exertion turning his upper body aggravates the pain and tylenol relieves the pain he underwent a ct scan the next day that revealed a thrombosed distal branch of the right portal vein no ascites or focal hepatic lesions were seen no hernias were seen he denies dyspnea and chest pain he denies fevers chills nausea vomiting and diarrhea he is able to tolerate food he denies dysuria and hematuria thrombosis of distal branch of right portal vein"/>
        </div>
    );
}

export default SamplePanel;